# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# set workdir
WORKDIR /app

# copy project files
COPY pyproject.toml .
COPY src ./src
COPY uv.lock .
COPY README.md .

# install dependencies
RUN pip install --no-cache-dir .

# default command
CMD ["spreadsheet-mcp"]
